//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::discord::Entity as Discord;
pub use super::player_evaluation::Entity as PlayerEvaluation;
pub use super::user::Entity as User;
