//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub administrator: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::discord::Entity",
        from = "Column::Id",
        to = "super::discord::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Discord,
}

impl Related<super::discord::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Discord.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
